---
- name: Infoblox config
  hosts: nios
  connection: local
  gather_facts: false

  collections:
    - infoblox.nios_modules
    
  tasks:

    - name: Setting up provider values
      set_fact:
       provider:
        host: "{{ nios }}"
        validate_certs: "False"

    - name: Configuring a reverse mapping zone
      infoblox.nios_modules.nios_zone:
        name: 10.10.10.0/24
        zone_format: IPV4
        state: present
        provider: "{{ provider }}"
      connection: local