---
- name: Infoblox config
  hosts: nios
  connection: local
  gather_facts: false

  collections:
    - infoblox.nios_modules
    
  tasks:

    - name: Setting up provider values
      set_fact:
       provider:
        host: "{{ nios }}"
        validate_certs: "False"

    - name: configure a CNAME record
      infoblox.nios_modules.nios_cname_record:
        name: cname.ansible.com
        canonical: realhost.ansible.com
        state: present
        comment: this is an optional test comment
        provider: "{{ provider }}"
      connection: local 
