---
- name: Run NIOS CLI commands on Infoblox
  hosts: all
  gather_facts: false
  # make sure to define the variable `ansible_ssh_private_key_file` either in the INI file 
  # or as part of the SSH key credential for the AAP machine
  
  tasks:
    - name: Run 'show grid status' on Infoblox NIOS
      ansible.builtin.shell: |
        ssh -o StrictHostKeyChecking=no {{ nios_username }}@{{ nios_host }} 'show grid status'
      register: show_grid_status
      no_log: false  # Set to true if you want to avoid logging sensitive data like passwords

    - name: Show the output of 'show grid status' command
      debug:
        msg: "{{ show_grid_status.stdout }}"
