---
- name: Infoblox config
  hosts: nios
  connection: local
  gather_facts: false

  collections:
    - infoblox.nios_modules
    
  tasks:

    - name: Setting up provider values
      set_fact:
       provider:
        host: "{{ nios }}"
        validate_certs: "False"

    - name: Updating an A record
      infoblox.nios_modules.nios_a_record:
        name: {new_name: a_new.ansible.com, old_name: a.ansible.com}
        ipv4: 192.168.10.1
        comment: this is an optional test comment
        state: present
        provider: "{{ provider }}"
      connection: local
